<div id="mcm_embed_signup" class="in">
	<div id="mcm-wrapper">
		<div id="mcm_dropdown-header">
			<div class="mcm-header-desktop">SIGN UP FOR OUR MAILING LIST AND GET 5% OFF ANY PURCHASE!</div>
			<div class="mcm-header-mobile">
				<div class="open">
					<b>SAVE 5% NOW</b> & get exclusive offers later.
				</div>
				<div class="closed">
					SIGN UP & <b>SAVE 5%</b>
				</div>
			</div>
			<button id="mcm_embed_close" class="mcm_embed_close">X</button>
		</div>
		<div id="mcm-dropdown-wrapper">
			<form
				action="https://bambibaby.us1.list-manage.com/subscribe/post-json?u=c4f5de820cf4d4eb94982a24b&id=578b601a12&c=?"
				method="post" id="mcm-embedded-subscribe-form" name="mcm-embedded-subscribe-form"
				class="validate" target="_blank" novalidate>
				<div class="mc-field-group" id="mcem-field-group">
					<input type="email" name="EMAIL"
						   class="required email" id="mcem-EMAIL" placeholder="Enter your email address">
				</div>
				<div style=" position: absolute; left: -5000px;">
					<input type="text" name="b_d07a4172c3cee103112a30ec7_9899287c59" value="">
				</div>
				<div id="mcem-subscribe">
					<input type="submit" value="Submit" name="submit" id="mc-embedded-subscribe"
						   class="button">
				</div>
				<div id="mcem-responses">
					<div class="response" id="mcem-error-response" style="display:none"></div>
					<div class="response" id="mcem-success-response" style="display:none"></div>
				</div>
			</form>
		</div>
	</div>
</div>
