<?php
//snowHelper
$_snowHelper = Mage::helper('snowpobox');

// aheadworks points
$awPoints = method_exists($this, 'getSummaryForCustomer');
if ($awPoints) {
    $summaryForCustomer = $this->getSummaryForCustomer();
    $textForPoints = Mage::helper('points/config')->getPointUnitName();
    $defaultValue = Mage::app()->getRequest()->getParam('payment[points_amount]');
}

// wageworx customercredit
$customerCredit = method_exists($this, 'isPartialPayment');
if ($customerCredit) {
    $isPartial = $this->isPartialPayment();
    $isCheckedCustomercredit = Mage::getSingleton('checkout/session')->getUseInternalCredit();
    if ($isPartial == 2 && $isCheckedCustomercredit) $this->getQuote()->getPayment()->setMethod('customercredit');
}

$billsafe = false;
?>
<?php if (!$methods = $this->getMethods()) : ?>
    <p>
        <?php echo $this->helper('checkout')->__('Oops, we couldn\'t get a shipping quote for you! Please double check your mailing address to ensure that you have entered your address correctly. For more information about our shipping policy and where we ship to,') ?> <a href="<?php echo $this->getUrl('return-policy') ?>"><?php echo $this->__('click here') ?>.
    </p>
<?php else : ?>
    <dl class="sp-method">
        <?php if ($awPoints && $this->pointsSectionAvailable()): ?>
            <dt>
                <input type="checkbox" name="payment[use_points]"
                       id="use_points"<?php echo (Mage::getSingleton('checkout/session')->getData('use_points')) ? ' checked="checked"' : '' ?>/>
                <label for="use_points"><?php echo $this->__('Use my %s', $textForPoints) ?></label>
            </dt>
            <dt>
                <input type="text" name="payment[points_amount]" value="<?php echo $defaultValue; ?>"
                       id="points_amount"/>
                <label
                    for="points_amount"><?php echo Mage::helper('points')->__('of %s %s (%s) available', $summaryForCustomer->getPoints(), $textForPoints, $this->getMoneyForPoints()) ?></label>
            </dt>
        <?php endif; ?>
        <div class="checkout__payment-method">
            <ul class="tabs">
                <?php $counter = 1; ?>
                <?php foreach ($this->getMethods() as $_method): $_code = $_method->getCode() ?>
                    <?php
                    if ($_snowHelper->getPoBoxStatus() != 1 && $_code == 'purchaseorder') {
                        continue;
                    }
                    $class = '';
                    if ( 1 == $counter ) {
                        $class = 'class="active"';
                    }
                    ?>
                    <li <?php echo $class; ?>>
                        <a class="tab-item-<?php echo $_code; ?>" href="#<?php echo $_code; ?>">
                            <?php
                                $methodTitle = $this->getMethodTitle($_method);

                                if ($_code == 'paypal_express' && !$methodTitle) {
                                    echo "Paypal Express Checkout";
                                } else { ?>
                                <?php echo $methodTitle ?>
                            <?php } ?>
                        </a>
                    </li>
                    <?php $counter++ ?>    
                <?php endforeach; ?>
            </ul>

            <?php
                // Reset Counter
                $counter = 1;
            ?>

            <?php foreach ($this->getMethods() as $_method): $_code = $_method->getCode() ?>
                <?php
                if ($_snowHelper->getPoBoxStatus() != 1 && $_code == 'purchaseorder') {
                    continue;
                }

                $class = '';
                if ( 1 == $counter ) {
                    $class = 'active';
                }
                ?>
                <div id="<?php echo $_code; ?>" class="checkout__payment checkout__payment--<?php echo $_code; ?> <?php echo $class; ?> clearfix">
                    <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
                        <?php if ( 'ccsave' == $_code ) : ?>
                            <div class="message">
                                <h4><?php echo $this->__( 'Secure Credit Card Payment' ); ?></h4>
                                <p><?php echo $this->__( 'This is a secure 128-bit SSL encrypted payment.' ); ?></p>
                            </div>
                        <?php endif; ?>
                        
                        <!-- Method Form -->
                        <?php echo $html; ?>

                    <?php endif; ?>
                    <ul class="form-list">
                        <li class="control same-as-billing">
                            <p><?php echo $this->__('Billing Address:'); ?></p>
                            <input type="checkbox" name="shipping[same_as_billing]" class="shippingsame_as_billing"
                                   id="shipping:same_as_billing" value="1"
                                   checked="checked" title="
                            <?php echo $this->__('Same as in shipping information') ?>"
                                   onclick="shipping.setSameAsBilling(this.checked)"
                                   class="checkbox shippingsame_as_billing"/><label for="shipping:same_as_billing">
                                <?php echo $this->__('Same as in shipping information') ?></label>
                        </li>
                    </ul>

                    <?php if ( 'ccsave' == $_code ) : ?>
                        <div class="logos">
                            <img class="credit-cards" src="<?php echo $this->getSkinUrl('images/creditcards.png'); ?>" alt="<?php echo $this->__('Credit Cards'); ?>">
                            <img class="verisign" src="<?php echo $this->getSkinUrl('images/verisign-checkout.png'); ?>" alt="<?php echo $this->__('Verisign'); ?>">
                        </div>
                    <?php endif; ?>
                </div>
                <?php if ('billsafe' == $_code) $billsafe = true; ?>
                <?php if ($customerCredit && $_code == 'customercredit' && $isPartial == -2) continue; // hide customer credit ?>

                <dt>
                    <?php if (sizeof($this->getMethods()) > 1): ?>
                        <?php if ($customerCredit) : ?>
                            <?php if ($_code == 'customercredit' && $isPartial == 1): ?>
                                <input id="p_method_<?php echo $_code ?>" value="1" type="checkbox"
                                       name="payment[use_internal_credit]"
                                       title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" class="checkbox"
                                       onclick="payment.switchMethod('<?php echo $_code ?>');"
                                       <?php if ($isCheckedCustomercredit) { ?>checked="checked"<?php } ?> />
                            <?php elseif ($_code == 'customercredit' && $isPartial == -1): ?>
                                <input id="p_method_<?php echo $_code ?>_disabled" disabled="disabled" value="1"
                                       type="checkbox" name="payment[use_internal_credit]"
                                       title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" class="checkbox"/>
                            <?php elseif ($_code == 'customercredit' && $isPartial == 0) : ?>
                                <input id="p_method_<?php echo $_code ?>_disabled" disabled="disabled"
                                       value="<?php echo $_code ?>" type="radio" name="payment[method]"
                                       title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" class="radio"/>
                            <?php else: ?>
                                <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio"
                                       name="payment[method]"
                                       title="<?php echo $this->htmlEscape($_method->getTitle()) ?>"
                                       onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if ($this->getSelectedMethodCode() == $_code): ?> checked="checked"<?php endif; ?>
                                       class="radio"/>
                            <?php endif; ?>
                        <?php else: ?>
                            <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio"
                                   name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>"
                                   onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if ($this->getSelectedMethodCode() == $_code): ?> checked="checked"<?php endif; ?>
                                   class="radio"/>
                        <?php endif ?>
                    <?php else: ?>
                        <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>"
                                                        type="radio" name="payment[method]"
                                                        onclick="payment.switchMethod('<?php echo $_code ?>')"
                                                        checked="checked" class="radio"/></span>
                    <?php endif; ?>

                    <label for="p_method_<?php echo $_code ?>">
                        <?php echo $this->getMethodTitle($_method) ?>
                        <?php if ($customerCredit && $_code == 'customercredit' && Mage::helper('customercredit')->isEnabledCodes()) : ?>
                            (<a href="<?php echo $this->getUrl('customercredit/') ?>"
                                target="_blank"><?php echo Mage::helper('customercredit')->__('Recharge') ?></a>)
                        <?php endif ?>
                        <?php echo $this->getMethodLabelAfterHtml($_method) ?>
                    </label>
                </dt>

                <?php $counter++ ?>
            <?php endforeach; ?>
        </div>
    </dl>

    <?php if (Mage::helper('core')->isModuleOutputEnabled('Netresearch_Billsafe') && !$billsafe) : ?>
        <p style="margin: 25px 0 10px;">
            <?php echo $this->getBillsafeLogo(); ?>
            <?php echo $this->__('BillSAFE payment is not available for this order'); ?>
        </p>
    <?php endif ?>

    <script type="text/javascript">
        //<![CDATA[
        <?php echo $this->getChildChildHtml('scripts'); ?>
        payment.init();
        //]]>
    </script>
    <?php $buyerprotect = $this->getChildHtml('buyerprotect');
    if (!empty($buyerprotect)) :
        echo $buyerprotect;
        ?>
        <script type="text/javascript">
            //<![CDATA[
            var trustedCheckbox = $('trusted_shops');
            trustedCheckbox.observe('click', function () {
                checkout.update('<?php echo $this->getUrl('firecheckout/index/buyerprotect', array('_secure' => true)) ?>');
            });
            $('trusted_shops-product').observe('change', function () {
                if (!trustedCheckbox.checked) {
                    return;
                }
                checkout.update('<?php echo $this->getUrl('firecheckout/index/buyerprotect', array('_secure' => true)) ?>');
            });
            //]]>
        </script>
    <?php endif ?>
<?php endif; ?>

<?php if ($awPoints && $this->pointsSectionAvailable()): ?>
    <script type="text/javascript">
        //<![CDATA[
        var customerPoints = <?php echo $summaryForCustomer->getPoints() ?>;
        var neededPoints = <?php echo $this->getNeededPoints() ?>;
        var limitedPoints = <?php echo $this->getLimitedPoints() ?>;

        $('use_points').disabled = $('points_amount').disabled = false;
        $('points_amount').value = Math.abs(Math.min(customerPoints, neededPoints, limitedPoints)).toFixed(0);

        <?php if ($amount = Mage::getSingleton('checkout/session')->getPointsAmount()) : ?>
        $('points_amount').value = <?php echo $amount ?>;
        <?php endif; ?>

        var pointsCheckbox = $('use_points');
        pointsCheckbox.observe('click', function () {
            checkout.update('<?php echo $this->getUrl('firecheckout/index/awpoints', array('_secure' => true)) ?>');
        });
        var pointsAmountChanged = function () {
            var points_amount = $('points_amount').value;
            if (isNaN(points_amount)) points_amount = 0;
            points_amount = Math.min(Math.abs(points_amount), customerPoints, neededPoints, limitedPoints);

            $('points_amount').value = Math.abs(points_amount).toFixed(0);

            if (!pointsCheckbox.checked) {
                return;
            }
            checkout.update('<?php echo $this->getUrl('firecheckout/index/awpoints', array('_secure' => true)) ?>');
        }
        $('points_amount').observe('change', pointsAmountChanged);
        //]]>
    </script>
<?php endif; ?>

<?php if ($customerCredit) : ?>
    <script type="text/javascript">
        //<![CDATA[
        el = $('p_method_customercredit');
        if (el) el.disabled = false;
        <?php if ($isPartial==1 && $isCheckedCustomercredit) { ?>payment.switchMethod('customercredit');<?php } ?>

        el && el.observe('click', function (e) {
            checkout.update(checkout.urls.payment_method);
            checkout.update('<?php echo $this->getUrl('firecheckout/index/awpoints', array('_secure' => true)) ?>');
        });
        //]]>
    </script>
<?php endif ?>

<?php $emjaTax = $this->getChildHtml('emja_taxrelief'); ?>
<?php if ($emjaTax) : ?>
    <dl>
        <?php echo $emjaTax; ?>
    </dl>
<?php endif ?>
<script>
    jQuery(document).ready(function () {
        jQuery("input.shippingsame_as_billing").prop("disabled", false);

        var methodLink = jQuery('ul.tabs li a').first(),
            methodCode = methodLink.attr('href');
        jQuery('div#checkout-payment-method-load dt').each(function (key, value) {
            jQuery(this).find('input').prop('checked', false);
        });
        
        jQuery('#p_method_' + methodCode.substring(1)).prop('checked', true);
        payment.switchMethod(methodCode.substring(1));
        jQuery('.checkout__payment-method select').selectric('refresh');

        
        jQuery('ul.tabs li a').click(function () {
            var method_code = jQuery(this).attr('href');
            jQuery('div#checkout-payment-method-load dt').each(function (key, value) {
                jQuery(this).find('input').prop('checked', false);
            });
            
            jQuery('#p_method_' + method_code.substring(1)).prop('checked', true);
            payment.switchMethod(method_code.substring(1));
            jQuery('.checkout__payment-method select').selectric('refresh');
        });

        jQuery('.shippingsame_as_billing').change(function () {
            if (jQuery(".shippingsame_as_billing").prop('checked')) {
                jQuery(".shippingsame_as_billing").prop('checked', true)
            } else {
                jQuery(".shippingsame_as_billing").prop('checked', false)
            }
        });
    });
</script>
