<?php
/* Add po box checkbox */
$_snowHelper = Mage::helper('snowpobox');
?>
<div class="cart main-cart">
    <div class="page-title title-buttons">
        <h1>
            <?php echo $this->__('Checkout, Step 1/2') ?>
            <span><?php echo $this->__('Step 1: Your Order Summary') ?></span>
        </h1>
        <?php if(!$this->hasError()): ?>
            <ul class="checkout-types top">
                <li>
                    <button type="submit" data-cart-item-update name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update Your Cart'); ?>" class="button button--blue button2 btn-update"><span><span><?php echo $this->__('Update Your Cart'); ?></span></span></button>
                </li>
                <?php foreach ($this->getMethods('top_methods') as $method): ?>
                    <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                        <li><?php echo $methodHtml; ?></li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <script>
        var tierPricesObject = {};
    </script>
    <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post" class="the-cart-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <fieldset>
            <div class="cart-table-wrapper">
                <table id="shopping-cart-table" class="data-table cart-table">
                    <col class="col-img" width="1" />
                    <col width="1" />
                    <col class="col-edit" width="1" />
                    <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                        <col class="col-wish" width="1" />
                    <?php endif ?>
                    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                        <col class="col-unit-price" width="1" />
                    <?php endif; ?>
                    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                        <col class="col-unit-price" width="1" />
                    <?php endif; ?>
                    <col width="1" />
                    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                        <col class="<?php if($this->helper('tax')->displayCartBothPrices()) echo 'col-total-excl'; else echo 'col-total'; ?>" width="1" />
                    <?php endif; ?>
                    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                        <col class="<?php if($this->helper('tax')->displayCartBothPrices()) echo 'col-total-incl'; else echo 'col-total'; ?>" width="1" />
                    <?php endif; ?>
                    <col class="col-delete" width="1" />

                    <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                    <thead>
                    <tr>
                        <th class="col-img" rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
                        <th rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Product Name') ?></span></th>
                        <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Item Quantity') ?></th>
                        
                        <!--                        <th class="col-edit a-center" rowspan="<?php //echo $mergedCells; ?>"><span class="nobr"><?php //echo $this->__('Style #') ?></span></th>-->
                        
                        <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                            <th class="col-wish a-center" rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Move to Wishlist') ?></span></th>
                        <?php endif ?>

                        <th class="col-unit-price a-center" colspan="<?php echo $mergedCells; ?>">
                            <span class="nobr">
                                <a href="javascript: void(0);" onclick="jQuery('#cart-units-description').toggle();" title="1 unit refers to 1 pair for socks or gloves; 1 unit refers to 1 garment for hats, leggings, and hosiery." style="text-decoration: underline;"><?php echo $this->__('Unit Price') ?></a>
                            </span>
                            <span id="cart-units-description" class="shadow">
                                <a href="javascript: void(0);" class="left" onclick="jQuery('#cart-units-description').hide()">X</a><br>
                                1 unit refers to 1 pair for socks or gloves.<br>
                                1 unit refers to 1 garment for hats, leggings, and hosiery.
                            </span>
                        </th>
                        <th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Subtotal') ?></th>
                        <th class="col-delete a-center" rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
                    </tr>
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                        <tr>
                            <th class="col-unit-price a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                            <th class="col-unit-price"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                            <th class="col-total-excl a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                            <th class="col-total-incl"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                        </tr>
                    <?php endif; ?>
                    </thead>
                    <tfoot>
                    <tr>
                        <td colspan="50" class="a-right">
                            <?php if($this->getContinueShoppingUrl()): ?>
                                <button type="button" title="<?php echo $this->__('Shop More') ?>" class="button btn-continue btn-inline" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><span><span><?php echo $this->__('Shop More') ?></span></span></button>
                            <?php endif; ?>
                            <button type="submit" name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update Shopping Cart'); ?>" class="button btn-update btn-inline"><span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>

                            <?php /*?>
                            <a id="link-cart-update" href="#">Test submit</a>
                            <script type="text/javascript">
                            jQuery(function($){
                                $('#link-cart-update').click(function() {
                                    $('.the-cart-form').submit();
                                });
                            });
                            </script>
                            <?php */?>

                            <?php /*?>
                            <button type="submit" name="update_cart_action" value="empty_cart" title="<?php echo $this->__('Clear Shopping Cart'); ?>" class="button btn-empty" id="empty_cart_button"><span><span><?php echo $this->__('Clear Shopping Cart'); ?></span></span></button>
                            <!--[if lt IE 8]>
                            <input type="hidden" id="update_cart_action_container" />
                            <script type="text/javascript">
                            //<![CDATA[
                                Event.observe(window, 'load', function()
                                {
                                    // Internet Explorer (lt 8) does not support value attribute in button elements
                                    $emptyCartButton = $('empty_cart_button');
                                    $cartActionContainer = $('update_cart_action_container');
                                    if ($emptyCartButton && $cartActionContainer) {
                                        Event.observe($emptyCartButton, 'click', function()
                                        {
                                            $emptyCartButton.setAttribute('name', 'update_cart_action_temp');
                                            $cartActionContainer.setAttribute('name', 'update_cart_action');
                                            $cartActionContainer.setValue('empty_cart');
                                        });
                                    }

                                });
                            //]]>
                            </script>
                            <![endif]-->
                            <?php */?>
                        </td>
                    </tr>
                    </tfoot>
                    <tbody>
                    <?php foreach($this->getItems() as $_item): ?>
                        <?php echo $this->getItemHtml($_item) ?>
                    <?php endforeach ?>
                    </tbody>
                </table>
                <script type="text/javascript">decorateTable('shopping-cart-table')</script>
                <!-- end: cart-table-wrapper -->
        </fieldset>
    </form>
    <script>
        PlusMinusObject.initPlusMinus(tierPricesObject, true);
    </script>
    <div class="cart-forms">
        <div class="cart-order">
            <div class="cart-order__input">
                <input type="checkbox" <?php if($_snowHelper->getPoBoxStatus()) : echo 'checked'; endif; ?> id="po-checkbox"  class="checkbox checkbox--order" data-url="<?php echo $_snowHelper->getAjaxUrl(); ?>" name="add-pobox" />
                
                <label for="purchase_order">
                    <strong><?php echo $this->__('Do you need a PO?' ); ?></strong> <?php echo $this->__('(Purchase Order)'); ?>
                    <br/>
                    <?php echo $this->__('If so, check this box on, and we\'ll follow up with you.'); ?>
                </label>
            </div>
            <div class="cart-order__input">
                <input type="checkbox" id="purchase_order_coupon" class="checkbox checkbox--order-coupon" name="purchase_order_coupon">
                <label for="purchase_order_coupon"><?php echo $this->__('I have a coupon.'); ?></label>
            </div>
            <?php echo $this->getChildHtml('coupon') ?>
        </div>
    </div>
    <div class="cart-totals-wrapper cart-collaterals nested-container">
        <div class="cart-totals cart-right-column grid12-4">
            <div class="totals grid-full alpha omega">
                <div class="totals-inner">
                    <?php echo $this->getChildHtml('totals'); ?>
                    <?php if(!$this->hasError()): ?>
                        <ul class="checkout-types bottom">
                             <li class="links">
                                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('sockbin_checkout_links')->toHtml(); ?>
                            </li>
                            <?php foreach ($this->getMethods('methods') as $method): ?>
                                <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                                    <li><?php echo $methodHtml; ?></li>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <li class="norton">
                                <img src="<?php echo $this->getSkinUrl('images/norton-secured.png'); ?>" alt="<?php echo $this->__('Norton'); ?>" />
                            </li>
                        </ul>
                    <?php endif; ?>
                </div>
            </div>
            <?php if ($tmpHtml = $this->getChildHtml('block_cart_below_totals')): ?>
                <div class="block_cart_below_totals grid-full alpha omega"><?php echo $tmpHtml; ?></div>
            <?php endif; ?>
        </div> <!-- end: cart-right-column -->
        <div class="cart-left-column grid12-8">
            <?php if ($tmpHtml = $this->getChildHtml('checkout.cart.extra')): ?>
                <div class="grid-full alpha omega">
                    <?php /* Extensions placeholder */ ?>
                    <?php echo $tmpHtml; ?>
                </div>
            <?php endif; ?>

            <?php if ($tmpHtml = $this->getChildHtml('block_cart_below_table')): ?>
                <div class="block_cart_below_table grid-full alpha omega"><?php echo $tmpHtml; ?></div>
            <?php endif; ?>

            <!--<div class="grid12-6 mobile-grid-half">
                <?php //if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
            </div>-->
        </div> <!-- end: cart-left-column -->
    </div>

    <?php echo $this->getChildHtml('crosssell') ?>

</div>
