<?php
/**
 * SHIPPING ADDRESS TEMPLATE
 */
$_layout = $this->getLayout();
$_dob = $_layout->createBlock('customer/widget_dob');
$_gender = $_layout->createBlock('customer/widget_gender');
$_taxvat = $_layout->createBlock('customer/widget_taxvat');
$_isCustomerLoggedIn = $this->isCustomerLoggedIn();
$_address = $this->getAddress();
$_prefix = 'billing';

$status = Mage::getStoreConfig('firecheckout/address_form_status');
if ('hidden' !== $status['postcode']) {
    $status['postcode'] = 'required'; // used to render asterisk
}
if (Mage::getStoreConfig('general/region/state_required')) {
    $status['region'] = 'required'; // used to render asterisk
}
$fields = array(
    'name' => array(),
    'region' => array(
        'label' => 'State',
        'required_to_render' => 1
    ),
    'email' => array(
        'class' => 'input-text validate-email email-field',
        'label' => 'Email',
        'status' => $_isCustomerLoggedIn ? 'hidden' : 'required'
    ),
    'telephone' => array(
        'class' => 'input-text',
        'label' => 'Telephone'
    ),
    'postcode' => array(
        'class' => 'input-text validate-zip-international',
        'label' => 'Zip Code'
    ),
    'country_id' => array(
        'label' => 'Country',
        'required_to_render' => 1
    ),
    'street1' => array(
        'class' => 'input-text',
        'label' => 'Address',
        'title' => 'Address',
        'name' => $_prefix . '[street][]',
        'value' => $_address->getStreet(1)
    ),
    'city' => array(
        'class' => 'input-text',
        'label' => 'City'
    ),
    'dob' => array(
        'status' => (!$_isCustomerLoggedIn && $_dob->isEnabled()) ? 'optional' : 'hidden'
    ),
    'gender' => array(
        'status' => (!$_isCustomerLoggedIn && $_gender->isEnabled()) ? 'optional' : 'hidden'
    ),
    'taxvat' => array(
        'status' => (!$_isCustomerLoggedIn && $_taxvat->isEnabled()) ? 'optional' : 'hidden'
    )
);

$addressHelper = $this->helper('customer/address');
if (method_exists($addressHelper, 'isVatAttributeVisible')) {
    $fields['vat_id'] = array(
        'status' => $addressHelper->isVatAttributeVisible() ? 'optional' : 'hidden',
        'class' => 'input-text ' . $addressHelper->getAttributeValidationClass('vat_id'),
        'label' => 'VAT Number'
    );
}
?>

<div id="billing-address" class="firecheckout-section">
    <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()) : ?>
        <div class="checkout__customer">
            <div class="checkout__customer-login">
                <strong><?php echo $this->__('Existing customer?'); ?></strong>
                <a href="<?php echo $this->getUrl('customer/account/login') ?>"><?php echo $this->__('Sign In'); ?></a>.
            </div>
            <div class="checkout__customer-shipping">
                <input type="checkbox" id="shipping_canada" name="shipping_canada">
                <label for="shipping_canada">
                    <?php echo $this->__('Shipping to Canada?'); ?>
                </label>
            </div>
        </div>
    <?php endif; ?>
    <?php if (!$this->canShip() || !Mage::getStoreConfig('firecheckout/general/shipping_address')): ?>
        <div class="block-title">
            <span><?php echo $this->helper('checkout')->__('Address'); ?></span>
        </div>
    <?php else: ?>
        <div class="block-title">
            <span><strong><?php echo $this->helper('checkout')->__('Your Shipping Information'); ?></strong></span>
        </div>
    <?php endif; ?>
    <div class="block-content">
        <ul class="form-list">
            
            <?php if ($this->customerHasAddresses()): ?>
                <li class="wide">
                    <label for="billing-address-select"><?php echo $this->helper('checkout')->__('Select a billing address from your address book or enter a new address.') ?></label>
                    <div class="input-box">
                        <?php echo $this->getAddressesHtmlSelect('billing') ?>
                    </div>
                </li>
            <?php endif; ?>
            
            <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
                <fieldset>
                    <input type="hidden" name="billing[address_id]" value="<?php echo $_address->getId() ?>"
                           id="billing:address_id"/>
                    <ul>
                        <?php foreach (Mage::helper('firecheckout/address')->getSortedFields() as $row) : ?>
                            <?php
                            $countVisible = 0;
                            $countRequiredToRender = 0;

                            foreach ($row as $key => $field) { // do not use break in this cycle to fill statuses for all fields
                                if (!isset($fields[$field])) { // billing address doesn't have all of the fields
                                    unset($row[$key]);
                                    continue;
                                }
                                if (empty($status[$field])) {
                                    if (!empty($fields[$field]['status'])) {
                                        $status[$field] = $fields[$field]['status'];
                                    } else {
                                        $status[$field] = 'required';
                                    }
                                }
                                if (!empty($fields[$field]['required_to_render'])) {
                                    $countRequiredToRender++;
                                }
                                if ('hidden' !== $status[$field]) {
                                    $countVisible++;
                                }
                            }

                            $isMulticolumn = ($countVisible > 1 || current($row) == 'name');
                            ?>

                            <?php if (!$countVisible && !$countRequiredToRender): continue; endif; ?>
                            
                            <?php foreach ($row as $field) : ?>
                                <?php $class = 'wide ' . $field; ?>
                                <li class="<?php echo $class; ?>" <?php echo $countVisible ? '' : ' style="display: none;"' ?>>
                                    <?php $required = ('required' === $status[$field]); ?>

                                    <?php if ('name' === $field) : ?>
                                        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($_address)->setFieldIdFormat($_prefix . ':%s')->setFieldNameFormat($_prefix . '[%s]')->toHtml() ?>

                                    <?php else : ?>

                                        <?php if ('hidden' === $status[$field]) :
                                            if (empty($fields[$field]['required_to_render'])) :
                                                continue;
                                            endif; ?>

                                            <div style="display: none;">
                                        <?php endif; ?>

                                        <?php if ($isMulticolumn) : ?>
                                        <div class="field">
                                    <?php endif; ?>

                                    <?php if ('dob' === $field): ?>
                                        <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat($_prefix . ':%s')->setFieldNameFormat($_prefix . '[%s]')->toHtml() ?>
                                    
                                    <?php elseif ('gender' === $field): ?>
                                        <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat($_prefix . ':%s')->setFieldNameFormat($_prefix . '[%s]')->toHtml() ?>
                                    
                                    <?php elseif ('taxvat' === $field): ?>
                                        <?php echo $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat($_prefix . ':%s')->setFieldNameFormat($_prefix . '[%s]')->toHtml() ?>
                                    
                                    <?php else: ?>
                                        
                                        <?php if ('country_id' !== $field) : ?>
                                            <label for="<?php echo $_prefix ?>:<?php echo $field ?>" class="<?php echo $required ? 'required' : '' ?>"><?php if ($required): ?>
                                                <em>*</em><?php endif; ?><?php echo $this->__($fields[$field]['label']) ?>
                                            </label>
                                        <?php endif; ?>

                                        <div class="input-box">
                                            
                                            <?php if ('country_id' === $field) : ?>
                                                <div class="country_id_select">
                                                    <?php echo $this->getCountryHtmlSelect($_prefix) ?>
                                                </div>
                                            <?php elseif ('region' === $field): ?>
                                                <div class="select-wrapper">
                                                    <span class="btn"></span>
                                                    <select id="<?php echo $_prefix ?>:region_id" name="<?php echo $_prefix ?>[region_id]" title="<?php echo(empty($fields[$field]['title']) ? $this->__($fields[$field]['label']) : $this->__($fields[$field]['title'])) ?>" class="validate-select<?php echo $required ? ' required-entry' : '' ?>">
                                                        <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                                    </select>
                                                </div>
                                                <script type="text/javascript">
                                                    //<![CDATA[
                                                    $('<?php echo $_prefix ?>:region_id').setAttribute('defaultValue', "<?php echo $_address->getRegionId() ?>");
                                                    //]]>
                                                </script>
                                                <input type="text" id="<?php echo $_prefix ?>:region" name="<?php echo $_prefix ?>[region]" value="<?php echo $this->escapeHtml($_address->getRegion()) ?>" title="<?php echo(empty($fields[$field]['title']) ? $this->__($fields[$field]['label']) : $this->__($fields[$field]['title'])) ?>" class="input-text<?php echo $required ? ' required-entry' : '' ?>" style="display:none;" />
                                            <?php else: ?>
                                                <?php
                                                if (isset($fields[$field]['value'])):
                                                    $value = $fields[$field]['value'];
                                                else:
                                                    $method = 'get' . ucfirst($field);
                                                    $value = $_address->{$method}();
                                                endif;
                                                ?>
                                                <input type="text" name="<?php echo(empty($fields[$field]['name']) ? $_prefix . '[' . $field . ']' : $fields[$field]['name']) ?>" id="<?php echo $_prefix ?>:<?php echo $field ?>" value="<?php echo $this->escapeHtml($value) ?>" title="<?php echo(empty($fields[$field]['title']) ? $this->__($fields[$field]['label']) : $this->__($fields[$field]['title'])) ?>" class="<?php echo $fields[$field]['class'] ?><?php echo $required ? ' required-entry' : '' ?>" />
                                            <?php endif ?>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ($isMulticolumn) : ?>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ('hidden' === $status[$field]) : ?>
                                        </div>
                                    <?php endif; ?>

                                <?php endif; ?>
                                </li>

                                <?php if ('street1' === $field) : ?>
                                    <?php for ($_i = 3, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                                        <li class="wide">
                                            <div class="input-box">
                                                <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="<?php echo $_prefix ?>[street][]" id="<?php echo $_prefix ?>:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($_address->getStreet($_i)) ?>" class="input-text" />
                                            </div>
                                    <?php endfor ?>
                                <?php endif; ?>

                            <?php endforeach; ?>
                            </li>
                        <?php endforeach; ?>

                        <?php $addressAttributes = $this->getChild('customer_form_' . $_prefix . '_address_user_defined_attributes'); ?>
                        <?php if ($addressAttributes): ?>
                            <?php $addressAttributes->setEntity($_address)->setEntityType('customer_address'); ?>
                            <?php $addressAttributes->setFieldIdFormat($_prefix . ':%1$s')->setFieldNameFormat($_prefix . '[%1$s]'); ?>
                            <?php echo $addressAttributes->setExcludeFileAttributes(true)->setShowContainer(false)->toHtml() ?>
                        <?php endif; ?>

                        <?php $customerAttributes = $this->getChild('customer_form_customer_user_defined_attributes'); ?>
                        <?php if ($customerAttributes): ?>
                            <?php $customerAttributes->setEntityModelClass('customer/customer')->setFieldIdFormat($_prefix . ':%1$s'); ?>
                            <?php $customerAttributes->setFieldNameFormat($_prefix . '[%1$s]')->setShowContainer(false); ?>
                            <?php echo $customerAttributes->setExcludeFileAttributes(true)->toHtml() ?>
                        <?php endif; ?>
                        <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()): ?>
                            <li class="control">
                                <input type="checkbox" name="billing[save_in_address_book]" value="1"
                                       title="<?php echo $this->__('Save in address book') ?>"
                                       id="billing:save_in_address_book" <?php if ($_address->getSaveInAddressBook()): ?> checked="checked"<?php endif; ?>
                                       class="checkbox"/><label
                                    for="billing:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
                            </li>
                        <?php else: ?>
                            <li class="no-display">
                                <input type="hidden" name="billing[save_in_address_book]" value="1"/>
                            </li>
                        <?php endif; ?>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                    </ul>
                </fieldset>
            </li>
            <?php /* Extensions placeholder */ ?>
            <?php echo $this->getChildHtml('checkout.onepage.billing.extra') ?>
            <?php if (Mage::helper('firecheckout')->canShowNewsletter()) : ?>
                <li class="newsletter control">
                </li>
            <?php endif; ?>
            <?php $additional = $this->getChildHtml('billing.additional.container');
            if (!empty($additional)) : ?>
                <li class="billing-additional">
                    <?php echo $additional; ?>
                </li>
            <?php endif; ?>
        </ul>
        <?php if (!$this->canShip() || !Mage::getStoreConfig('firecheckout/general/shipping_address')): ?>
            <input type="hidden" name="billing[use_for_shipping]" value="1"/>
        <?php else: ?>
            <input type="hidden" name="billing[use_for_shipping]" id="billing:use_for_shipping"
                   value="<?php if ($this->isUseBillingAddressForShipping()): ?>1<?php else: ?>0<?php endif; ?>"/>
        <?php endif; ?>
        <script type="text/javascript">
            //<![CDATA[
            var billing = new Billing();
            var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
            //]]>
        </script>
    </div>
</div>
<script>
    jQuery(document).ready(function () {
        jQuery("select[title='Country']").find("option[value='US']").prop('selected', true);
        billingRegionUpdater.update();

        jQuery('#shipping_canada').change(function () {
            if (jQuery("#shipping_canada").prop('checked')) {
                jQuery("select[title='Country']").find("option[value='CA']").prop('selected', true);
                billingRegionUpdater.update();
            } else {
                jQuery("select[title='Country']").find("option[value='US']").prop('selected', true);
                billingRegionUpdater.update();
            }
        });
    });
</script>
