<?php
$comment = Mage::getStoreConfig('firecheckout/general/comment');
$salesrep = Mage::getStoreConfig('salesrep/setup/enabled') && Mage::getStoreConfig('salesrep/step_setup/step_enabled');
$checkoutFields = $this->getChildHtml('checkoutfields');
$snowHelper = Mage::helper('snowpobox');
?>

<?php if ($comment || $salesrep || $checkoutFields) : ?>
    <div id="checkout-additional" class="firecheckout-section">
        <div class="block-title">
            <span><?php echo $this->__('Additional Information') ?></span>
        </div>
        <div class="block-content">
            <?php if (Mage::getStoreConfig('firecheckout/general/comment')) : ?>
                <ul class="form-list form-comment">
                    <li class="wide">
                        <label for="order-comment">
                            <?php echo $this->helper('sales')->__('Comment') ?>
                        </label>
                        <div class="input-box">
                            <textarea name="order-comment" 
                                      id="order-comment" rows="5"
                                      cols="25"><?php echo trim(Mage::getSingleton('customer/session')->getOrderCustomerComment()) ?></textarea>
                        </div>
                    </li>
                </ul>
            <?php endif; ?>

            <?php if (Mage::getStoreConfig('salesrep/setup/enabled') && Mage::getStoreConfig('salesrep/step_setup/step_enabled')) : ?>
                <?php $admins = Mage::helper('salesrep')->getUsersList(); ?>
                <ul class="form-list">
                    <li>
                        <label for="getvoice"
                               class="required"><em>*</em><?php echo Mage::getStoreConfig('salesrep/step_setup/step_label') ?>
                        </label>
                        <div class="input-box">
                            <select id="getvoice" name="getvoice" class="validate-select">
                                <option value=""></option>
                                <option
                                    value="<?php echo $this->__('No Sales Representative') ?>"><?php echo $this->__('No Sales Representative') ?></option>
                                <?php foreach ($admins as $admin): ?>
                                    <option value="<?php echo $admin['label'] ?>"><?php echo $admin['label'] ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div style="display: none;" id="advice-validate-select-getvoice" class="validation-advice">
                            <?php echo Mage::getStoreConfig('salesrep/step_setup/step_error_msg') ?>
                        </div>
                    </li>
                </ul>
            <?php endif; ?>

            <?php echo $checkoutFields ?>
        </div>
    </div>
<?php endif; ?>

<div class="norton-guarantee">
    <a class="norton-guarantee__link" target="_blank" href="https://my.nortonshoppingguarantee.com/Web/Seal/VerifySeal.aspx?PublicToken=dboRyPvallfMX%2f5qdl1XNw7DGoUwmedE8Gv9Kilz%2bMOjQrvH5pVALGscZ8ND0viNaQylh970ISJFNW8VTsPweg%3d%3d&MSPHASH=&G=1">
        <img class="norton-guarantee__image" src="<?php echo $this->getSkinUrl('images/norton_shopping_guarantee_banner_in.jpg'); ?>" alt="<?php echo $this->__('Norton Guarantee'); ?>" />
    </a>
</div>
<div class="norton-guarantee">
     <fieldset>
        <ul>
            <li class="wide">
                <label for="ordercomment-comment"><?php echo Mage::helper('ordercomment')->__('Order Comment') ?></label>
                <div class="input-box">
                    <textarea id="ordercomment-comment" class="input-text validation-passed" name="ordercomment[comment]" title="<?php echo $this->__('Order Comment') ?>" rows="5" cols="10"></textarea>
                </div>
            </li>
        </ul>
    </fieldset>
</div>

<div id="checkout-review" class="firecheckout-section checkout__order-total">
    <div class="message">
        <h4><?php echo $this->__('What will happen next?') ?></h4>
        <?php $agreements = $this->getChildHtml('agreements') ?>
        <?php if (!empty($agreements)) : ?>
            <div id="agreements-wrapper">
                <?php echo $agreements; ?>
            </div>
        <?php endif; ?>
        <p>
            <?php echo $this->__('We will receive your order, bill your credit card and ship it in 24-48 hours.'); ?>
        </p>
    </div>

    <div class="checkout__order-box">
        <div class="price-box">
            <strong><?php echo $this->__('Total'); ?></strong>
            <span>
                <strong>
                    <span class="total">
                        <?php echo $snowHelper->getTotal(); ?>
                    </span>
                </strong>
            </span>
        </div>
        <div id="checkout-review-submit">
            <div class="buttons-set" id="review-buttons-container">
                <button
                        type="button"
                        title="<?php echo $this->__('Submit Your Order') ?>" class="button btn-checkout button--green button--larg"
                        onclick="checkout.save(); return false;">
                    <span><span><?php echo $this->__('Submit Your Order') ?></span></span></button>
            <span class="please-wait" id="review-please-wait" style="display:none;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"
                     alt="<?php echo $this->__('Submitting order information...') ?>"
                     title="<?php echo $this->__('Submitting order information...') ?>"
                     class="v-middle"/> <?php echo $this->__('Submitting order information...') ?>
            </span>
            </div>
        </div>
    </div>
    
    <div id="checkout-review-load" class="hidden">
        <?php echo $this->getChildHtml('info') ?>
    </div>

    <?php
    $html = $this->getChildHtml('review_after');
    if ($html || $blockId = Mage::getStoreConfig('firecheckout/additional_content/reviewtable_after')) : ?>
        <div class="firecheckout-items-after">
            <?php // echo $blockId ? $this->getLayout()->createBlock('cms/block')->setBlockId($blockId)->toHtml() : ''; ?>
            <?php // echo $html ?>
        </div>
    <?php endif; ?>
    <script type="text/javascript">
        //<![CDATA[
        //review = new Review(); // dummy class for various payment methods
        //]]>
    </script>
</div>
