<?php if ($this->getQuote()->isVirtual()) : return; endif; ?>
<div class="block-title">
    <span><strong><?php echo $this->__('Shipping Method'); ?>:</strong></span>
</div>
<div id="shipping-method" class="firecheckout-section">
    <div class="block-content">
        <div id="checkout-shipping-method-load">
            <?php echo $this->getChildHtml('available') ?>
        </div>
        
        <script type="text/javascript">
        //<![CDATA[
            var shippingMethod = new ShippingMethod('shipping-method');
        //]]>
        </script>
        
        <?php echo $this->getChildHtml('delivery_date') ?>
        
        <div id="onepage-checkout-shipping-method-additional-load">
            <?php echo $this->getChildHtml('additional') ?>
        </div>

        <?php echo $this->getChildHtml('wsa-accessorials') ?>
    </div>
</div>