<?php 
/**
 * @category    Mana
 * @package     Mana_Filters
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/** 
 * Template for showing options for filter as a HTML list 
 * @author Mana Team
 * Injected instead of standard catalog/layer/filter.phtml in Mana_Filters_Block_Filter_Attribute constructor.
 * This template is overridden by copying (template body was pasted from catalog/layer/filter.phtml 
 * and modified as needed). All changes are marked with comments.
 */
/* @var $this Mana_Filters_Block_Filter_Attribute */
?>
<?php
    $anyUrl = false;
?>
<?php foreach ($this->getItems() as $_item): ?>
    <?php
        if (!$anyUrl) {
            $anyUrl = true;
    ?>
        <option value="<?php echo $this->urlEscape($_item->getRemoveUrl()) ?>">
            <?php echo $this->__("Any"); ?>
        </option>
    <?php } ?>
    <?php
        if ($_item->getMSelected()) {
            $selected = "selected='selected'";
        } else {
            $selected = "";
        }
    ?>
    <option value="<?php echo $this->urlEscape($_item->getUrl()) ?>" <?php echo $selected; ?>>
        <?php echo $this->escapeHtml($_item->getLabel()) ?>
        <?php if (Mage::getStoreConfigFlag('mana_filters/display/count')) : ?>
            (<?php echo $_item->getCount() ?>)
        <?php endif; ?>
    </option>
<?php endforeach ?>
